# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_service', '0002_auto_20170320_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacility',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='healthfacility', to='simple_locations.Area'),
        ),
    ]
