# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_service', '0003_update_area_related_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacility',
            name='catchment_areas',
            field=models.ManyToManyField(blank=True, null=True, related_name='_healthfacility_catchment_areas_+', to='simple_locations.Area'),
        ),
    ]
