# Generated by Django 2.2.12 on 2020-04-24 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_service', '0004_catchment_areas_is_blankable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacility',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='healthfacility', to='simple_locations.Area'),
        ),
    ]
